apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service_name}}
spec:
  type: NodePort
  selector:
    app: {{.Values.app_name}}
  ports: 
    - name: {{.Values.port_name}}
      protocol: TCP
      port: {{.Values.port_number}}
      nodePort: {{.Values.nodeport_number}}
