apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-jenkins
  labels:
    app: myapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: myapp      
  template:
    metadata:
      name: jenkinsdeploy
      labels:
        app: myapp
    spec:
      containers:
        - name: jenkins
          image: jenkins:2.60.3

--- 
apiVersion: v1
kind: Service
metadata: 
  name: my-jenkins
spec:
  type: NodePort
  selector:
     app: myapp
  ports:
    - name: port1
      protocol: TCP
      port: 8080
      nodePort: 30088
    - name: port2
      protocol: TCP
      port: 50000
      nodePort: 30888 
