apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: girish
  name: my-jenkins1
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp      
  template:
    metadata:
      name: jenkinsdeploy
      labels:
        app: myapp
    spec:
      containers:
        - name: jenkins
          image: jenkins:2.60.2

--- 
apiVersion: v1
kind: Service
metadata: 
  namespace: girish
  name: my-jenkins1
spec:
  type: NodePort
  selector:
     app: myapp
  ports:
    - name: port1
      protocol: TCP
      port: 8080
      nodePort: 30009
    - name: port2
      protocol: TCP
      port: 50000
      nodePort: 30090 
