apiVersion: v1
kind: PersistentVolume 
metadata:
  name: myvolume
spec: 
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /dev/root
    server: 172.31.11.197

