apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{.Values.deploy_name}}
  labels:
    app: {{.Values.app_name}}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: {{.Values.noofreplicas}}
  selector:
    matchLabels:
      app: {{.Values.app_name}}      
  template:
    metadata:
      name: {{.Values.template_deploy_name}}
      labels:
        app: {{.Values.app_name}}
    spec:
      containers:
        - name: {{.Values.container_name}}
          image: {{.Values.image_name}}:{{.Values.image_version}}

--- 
apiVersion: v1
kind: Service 
metadata: 
  name: {{.Values.service_name}}
spec:
  type: NodePort
  selector:
     app: {{.Values.app_name}}
  ports:
    - name: {{.Values.port1_name}}
      protocol: TCP
      port: {{.Values.port1_number}}
      nodePort: {{.Values.nodeport1_name}}
    - name: {{.Values.port2_name}}
      protocol: TCP
      port: {{.Values.port2_number}}
      nodePort: {{.Values.nodeport2_name}}
